### ISSUE TITLE
What is Isaackogan? Why do we need it?

### ISSUE THREAD

**Issue by ivanocj** [zerodytrash/TikTok-Live-Connector#110]
Anyone know if there's a way to keep everything inside our own server?

Not sure why it needs to query the host below: 

url: 'https://tiktok.isaackogan.com/webcast/fetch/?room_id=7228588818307451654&client=ttlive-node&uuc=1&apiKey=&isSignRedirect=1&iph=797663489d2b7a9cded50b27f33dc8e1',

**Comment by ivanocj** [comment]
Anyone knows what is the role of singProviderHost on tiktokSignatureProvider.js? 

Hi @zerodytrash can you please help? thanks in advance.

``` javascript
let config = {
  enabled: true,
  signProviderHost: 'https://tiktok.isaackogan.com/',
  extraParams: {}
};
```

**Comment by Pulse-Git** [comment]
@ivanocj didnt looked into the, but probally as the name said "sign provider"

**Comment by ivanocj** [comment]
> @ivanocj didnt looked into the source, but probally as the name said "sign provider"
> 
> look at this: [#108 (comment)](https://github.com/zerodytrash/TikTok-Live-Connector/issues/108#issuecomment-1529100324)

If you look better, there is some sort of backend going on it. Since is this code is closed to us, I believe this is sort of some backdoor.

**Comment by Pulse-Git** [comment]
> > @ivanocj didnt looked into the source, but probally as the name said "sign provider"
> > look at this: [#108 (comment)](https://github.com/zerodytrash/TikTok-Live-Connector/issues/108#issuecomment-1529100324)
> 
> If you look better, there is some sort of backend going on it. Since this source code is closed to us, I believe this is sort of some backdoor.

backdoor to what? you dont provide any credentials? they CANT login into your account

**Comment by ivanocj** [comment]
> > > @ivanocj didnt looked into the source, but probally as the name said "sign provider"
> > > look at this: [#108 (comment)](https://github.com/zerodytrash/TikTok-Live-Connector/issues/108#issuecomment-1529100324)
> > 
> > 
> > If you look better, there is some sort of backend going on it. Since this source code is closed to us, I believe this is sort of some backdoor.
> 
> backdoor to what? you dont provide any credentials? they CANT login into your account

backdoor to a generic account - who knows ? Why this part isn't open sourced to everyone? Do you feel comfortable?

**Comment by Pulse-Git** [comment]
> > > > @ivanocj didnt looked into the source, but probally as the name said "sign provider"
> > > > look at this: [#108 (comment)](https://github.com/zerodytrash/TikTok-Live-Connector/issues/108#issuecomment-1529100324)
> > > 
> > > 
> > > If you look better, there is some sort of backend going on it. Since this source code is closed to us, I believe this is sort of some backdoor.
> > 
> > 
> > backdoor to what? you dont provide any credentials? they CANT login into your account
> 
> backdoor to a generic account - who knows ? Why this part isn't open sourced to everyone? Do you feel comfortable?

mh they said why its not open source.
if it is open to users have unlimited access to the tiktok api without any rate limit. i think they got an rate limit free api key for this repo and they are not allowed to share it publicly, thats why they build an own service which wraps it with an rate limit etc

**Comment by ivanocj** [comment]
Absolutely, and that's why I think this part is sketchy. See the iph? What is this, how it is generated? how the room_id is retrieved? What else this isaac kogan backend doing? 

```
[iph=797663489d2b7a9cded50b27f33dc8e1](https://tiktok.isaackogan.com/webcast/fetch/?room_id=7228588818307451654&client=ttlive-node&uuc=1&apiKey=&isSignRedirect=1&iph=797663489d2b7a9cded50b27f33dc8e1)'
```

**Comment by Pulse-Git** [comment]
@ivanocj maybe that is generated from their service as an way to access the api? who knows? it doesnt matter

**Comment by ivanocj** [comment]
> @ivanocj maybe that is generated from their service as an way to access the api? who knows? it doesnt matter

it matters to me since I don't want to depend on another service being available or not.

**Comment by Pulse-Git** [comment]
@ivanocj than dont rely on this repo. build your own and ask tiktok for unlimited access

**Comment by Pulse-Git** [comment]
@isaackogan oh always thought tiktok grant unlimited access to you and they just said you need to protect it.
so basically you just reverse engineered the app/website and looked how to generate the signature.

**Comment by isaackogan** [comment]
> @isaackogan oh always thought tiktok grant unlimited access to you and they just said you need to protect it. so basically you just reverse engineered the app/website and looked how to generate the signature.

Yes (Zerody found the method), it was not easy to discover.

**Comment by Pulse-Git** [comment]
@isaackogan sounds a bit scary to me, when people build something big with this library and tiktok will block and close the way to generate the signature. but in general good work from you guys

**Comment by isaackogan** [comment]
That'd be why one of the first lines of the project says:

> NOTE: This is not an official API. It's a reverse engineering project.

**Comment by iProGamer** [comment]
😂😂😂😂😂😂😂

**Comment by isaackogan** [comment]
For future references of this page, please see the wiki for the full breakdown:

https://github.com/isaackogan/TikTokLive/wiki/Signature-Server

**Comment by ivanocj** [comment]
> > What is Isaackogan?
> 
> This is hilarious. Hi, I'm an isaackogan. It's my name.
> 
> What you're looking at is the signature provider for TikTok LIVE. TikTok initially did **not** want people willy nilly scraping their livestreams. They added tokens which only their site should be able to generate so that requests to TikTok only come from their site and not scrapers like us. So, we added token reversal tools to this library to generate them. This got our library noticed by the company and blocked for weeks on end.
> 
> Zerody & me created the sign server to quite literally "hide" the generation of these tokens so that TikTok would stop blocking us. And they did. We have not been blocked by TikTok for 6 months.
> 
> > Since this source code is closed to us, I believe this is sort of some backdoor.
> 
> Respectfully, this is moronic. It's a GET request with no account information. You are at higher risk when you log on a porn website—at least they can sell your likely strange preferences and serve you ads based on them. The entire code for the library is open source. You would **be able to see** any backdoors because Python and JavaScript are not compiled languages. The source code is right there.
> 
> > it matters to me since I don't want to depend on another service being available or not.
> 
> This is a valid concern. To alleviate it, make your own library.

Hi Isaac, sorry... I didn't meant to be rude. And thanks for taking time to explain it in details. I'm now working on my own scraper for Tiktok LIVE, just got most of the features working actually with Puppeteer only and am testing the rate limits of Tiktok. As of today, things are working as expected, very few bumps in the way. Good luck to you all!

**Comment by isaackogan** [comment]
Glad to hear it! I am sorry for the rudeness in my messages. It's not an excuse, but it was a very frustrating couple of days with everything breaking down. I shouldn't have said that. 

Take care,
Isaac
