### ISSUE TITLE
Failed to sign request: timeout of 5000ms exceeded

### ISSUE THREAD

**Issue by voltailor** [zerodytrash/TikTok-Live-Connector#126]
Error: Failed to sign request: timeout of 5000ms exceeded; URL: https://webcast.tiktok.com/webcast/im/fetch/?aid=1988&app_language=en-US&app_name=tiktok_web&browser_language=en&browser_name=Mozilla&browser_online=true&browser_platform=Win32&browser_version=5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F102.0.5005.63+Safari%2F537.36&cookie_enabled=true&cursor=&internal_ext=&device_platform=web&focus_state=true&from_page=user&history_len=4&is_fullscreen=false&is_page_visible=true&did_rule=3&fetch_rule=1&identity=audience&last_rtt=0&live_id=12&resp_content_type=protobuf&screen_height=1152&screen_width=2048&tz_name=Europe%2FBerlin&referer=https%3A%2F%2Fwww.tiktok.com%2F&root_referer=https%3A%2F%2Fwww.tiktok.com%2F&version_code=180800&webcast_sdk_version=1.3.0&update_version_code=1.3.0&room_id=7265688178927962922

Have you any idea how to fix it?

**Comment by northoniserhardt** [comment]
Same here

**Comment by northoniserhardt** [comment]
![image](https://github.com/zerodytrash/TikTok-Live-Connector/assets/32493494/cf8618c3-7de1-4e1c-8ce7-62679a2831a7)

**Comment by Velozity** [comment]
+1

**Comment by qrq** [comment]
Same :(

**Comment by supergenius88** [comment]
**Same situation. Was definitely working yesterday. Here's an example of a full output stack from server start:**

New connection from origin http://localhost:8081/
WRAPPER @@dontworryjustbreathe: Error event triggered: Error while connecting, Error: Failed to sign request: timeout of 5000ms exceeded; URL: https://webcast.tiktok.com/webcast/im/fetch/?aid=1988&app_language=en-US&app_name=tiktok_web&browser_language=en&browser_name=Mozilla&browser_online=true&browser_platform=Win32&browser_version=5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F102.0.5005.63+Safari%2F537.36&cookie_enabled=true&cursor=&internal_ext=&device_platform=web&focus_state=true&from_page=user&history_len=4&is_fullscreen=false&is_page_visible=true&did_rule=3&fetch_rule=1&identity=audience&last_rtt=0&live_id=12&resp_content_type=protobuf&screen_height=1152&screen_width=2048&tz_name=Europe%2FBerlin&referer=https%3A%2F%2Fwww.tiktok.com%2F&root_referer=https%3A%2F%2Fwww.tiktok.com%2F&version_code=180800&webcast_sdk_version=1.3.0&update_version_code=1.3.0&room_id=7266524677974133547
{
  info: 'Error while connecting',
  exception: Error: Failed to sign request: timeout of 5000ms exceeded; URL: https://webcast.tiktok.com/webcast/im/fetch/?aid=1988&app_language=en-US&app_name=tiktok_web&browser_language=en&browser_name=Mozilla&browser_online=true&browser_platform=Win32&browser_version=5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F102.0.5005.63+Safari%2F537.36&cookie_enabled=true&cursor=&internal_ext=&device_platform=web&focus_state=true&from_page=user&history_len=4&is_fullscreen=false&is_page_visible=true&did_rule=3&fetch_rule=1&identity=audience&last_rtt=0&live_id=12&resp_content_type=protobuf&screen_height=1152&screen_width=2048&tz_name=Europe%2FBerlin&referer=https%3A%2F%2Fwww.tiktok.com%2F&root_referer=https%3A%2F%2Fwww.tiktok.com%2F&version_code=180800&webcast_sdk_version=1.3.0&update_version_code=1.3.0&room_id=7266524677974133547
      at signRequest (/Users/localhostguy/Documents/chatbot/node_modules/tiktok-live-connector/dist/lib/tiktokSignatureProvider.js:86:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async TikTokHttpClient._buildUrl2 (/Users/localhostguy/Documents/chatbot/node_modules/tiktok-live-connector/dist/lib/tiktokHttpClient.js:98:15)
      at async TikTokHttpClient.getDeserializedObjectFromWebcastApi (/Users/localhostguy/Documents/chatbot/node_modules/tiktok-live-connector/dist/lib/tiktokHttpClient.js:63:15)
      at async WebcastPushConnection._fetchRoomData2 (/Users/localhostguy/Documents/chatbot/node_modules/tiktok-live-connector/dist/index.js:542:25)
      at async WebcastPushConnection.connect (/Users/localhostguy/Documents/chatbot/node_modules/tiktok-live-connector/dist/index.js:273:7)
}
WRAPPER @@dontworryjustbreathe: Connection failed, Error: Failed to sign request: timeout of 5000ms exceeded; URL: https://webcast.tiktok.com/webcast/im/fetch/?aid=1988&app_language=en-US&app_name=tiktok_web&browser_language=en&browser_name=Mozilla&browser_online=true&browser_platform=Win32&browser_version=5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F102.0.5005.63+Safari%2F537.36&cookie_enabled=true&cursor=&internal_ext=&device_platform=web&focus_state=true&from_page=user&history_len=4&is_fullscreen=false&is_page_visible=true&did_rule=3&fetch_rule=1&identity=audience&last_rtt=0&live_id=12&resp_content_type=protobuf&screen_height=1152&screen_width=2048&tz_name=Europe%2FBerlin&referer=https%3A%2F%2Fwww.tiktok.com%2F&root_referer=https%3A%2F%2Fwww.tiktok.com%2F&version_code=180800&webcast_sdk_version=1.3.0&update_version_code=1.3.0&room_id=7266524677974133547

**Comment by LucasLopesCaldas** [comment]
For me it worked again!

**Comment by voltailor** [comment]
Yes, it works now.
