### ISSUE TITLE
Randomly stops working without error

### ISSUE THREAD

**Issue by spdesmith** [zerodytrash/TikTok-Live-Connector#141]
My scraper scraps profile pictures and comments and just the average stuff. Sometimes it runs for 4 hours straight and then stops working and then sometimes it works for 5 minutes and then stops working. It doesn't say any error, even when I added the handle error. So I'm not sure what's wrong and why it's stopping randomly. Same thing would happen with the python live scrapper. The stream is still running, I have to manually close and reopen it which is annoying. There's just a blinking line when the problem happens. Anyone get this problem too? Other than that it's working perfectly. 

Extra details:
Using a udp server to send messages to somewhere else, now using asyncio instead of https to download profile picture (could be the problem not sure)

**Comment by MikiGamer** [comment]
> My scraper scraps profile pictures and comments and just the average stuff. Sometimes it runs for 4 hours straight and then stops working and then sometimes it works for 5 minutes and then stops working. It doesn't say any error, even when I added the handle error. So I'm not sure what's wrong and why it's stopping randomly. Same thing would happen with the python live scrapper. The stream is still running, I have to manually close and reopen it which is annoying. There's just a blinking line when the problem happens. Anyone get this problem too? Other than that it's working perfectly. 
> 
> 
> 
> Extra details:
> 
> Using a udp server to send messages to somewhere else, now using asyncio instead of https to download profile picture (could be the problem not sure)

Have you tried to use **_disconnected_** for event as close of connection?
Also you could make some kind of ping for your intern system, where  you check if last received data was for example 60 secs.
