### ISSUE TITLE
Error: Failed to retrieve room_id from page source. Your IP or country might be blocked by TikTok.

### ISSUE THREAD

**Issue by dragosite** [zerodytrash/TikTok-Live-Connector#158]
I am getting this error locally, using the python version as well as the example website (https://tiktok-chat-reader.zerody.one)?

**Comment by zerodytrash** [comment]
Please update the library to the latest version. I just did that with the chat reader example.

**Comment by dragosite** [comment]
Hi @zerodytrash 

Thanks for you quick reply, now works!

Thanks,
Dragos
