### ISSUE TITLE
Failed to connect Error: Missing cursor in initial fetch response.

### ISSUE THREAD

**Issue by Tutuldot** [zerodytrash/TikTok-Live-Connector#180]
Hi,

Recently I experience Failed to connect Error: Missing cursor in initial fetch response. error message when connecting to data data. how to resolve this issue? is adding sessionid will fix this?

Thank you.

Ant

**Comment by Tutuldot** [comment]
Btw, how to get session id of tiktok account?

**Comment by Bton123** [comment]
also getting this

**Comment by calv-io-n** [comment]
Yes this is happening to the demo of TikTokLIve Chat

**Comment by cjvergara** [comment]
Error: Missing cursor in initial fetch response. - Can't connect to any streams even on chat demo site.

**Comment by esalvi** [comment]
Same problem

**Comment by calv-io-n** [comment]
![image](https://github.com/zerodytrash/TikTok-Live-Connector/assets/45134088/358d3705-0bb5-44e5-b22f-c2cc605b82e8)

The output of the initial webcast fetch is an empty object

![image](https://github.com/zerodytrash/TikTok-Live-Connector/assets/45134088/856ab284-318a-4fb9-89e1-3b4aa3ab0841)

**Comment by calv-io-n** [comment]
I was able to kind of get it working @zerodytrash but I don't have enough time to read the entire codebase but this produced closer results:

![image](https://github.com/zerodytrash/TikTok-Live-Connector/assets/45134088/206cb898-239e-4524-81cd-d572962fba8a)

**Comment by Wannes-Vanoyenbrugge** [comment]
@calv-io-n could you paste the code? Best wishes

**Comment by calv-io-n** [comment]
> @calv-io-n could you paste the code? Best wishes

It was only temporarily working - it's only temporarily working the TikTokLive Chat

Updated to `^1.1.5`

**Comment by esalvi** [comment]
1.1.5 is working now. In my case, last "Error: Missing cursor in initial fetch response" was 2 hours ago

**Comment by Tutuldot** [comment]
its working now thanks a lot.

**Comment by jillbourque** [comment]
This is still happening for me.
