### ISSUE TITLE
Internal Server Error while connect to Server

### ISSUE THREAD

**Issue by bradlynpeter** [zerodytrash/TikTok-Live-Connector#201]
Please help to fix the problem I am experiencing, maybe because there is an update from TikTok Live Studio which is causing this problem....

**Comment by baskodeng** [comment]
same heree....
i can not connect to server with error message "Internal Server Error"....

**Comment by vivevainspira** [comment]
Many comments regarding this error, me having problem too, internal server error

**Comment by chesskinx** [comment]
kinx can't connect too...internal server errrrorrrr

**Comment by marioschwezenger** [comment]
@zerodytrash please broo, please help to fix this broo...

**Comment by bradlynpeter** [comment]
Thank you @zerodytrash, problem was resolved....

yo guys you can try to connect again guys....
