### ISSUE TITLE
Error Response Status: 503, Service Unavailable

### ISSUE THREAD

**Issue by webjoyable** [zerodytrash/TikTok-Live-Connector#203]
Has anyone managed to successfully connect to any live room today? I'm getting 503 after single connection.

**Comment by bensh90** [comment]
I'm havin the same issue today. I think tiktok might have changed something again to prevent that form of webscraping.
if I input the URL directly into the browser and change some parameters, it shows 503 API is not ready yet. But it doesn't really make any sense.

**Comment by xaricipul** [comment]
i'm having the same issue

**Comment by bensh90** [comment]
it runs again. Seems to have been a temporary issue. I guess this could be closed

**Comment by webjoyable** [comment]
It seems normal now. Might be something due to Tiktok servers
