### ISSUE TITLE
ERR_CONNECTION_REFUSED,

### ISSUE THREAD

**Issue by bradlynpeter** [zerodytrash/TikTok-Live-Connector#207]
hello @zerodytrash can you help me with this error ?
i cant connect to your server right now...

**Comment by mrvictordiaz2** [comment]
Hello @zerodytrash, I got an error and can't connect. Please fix this!

**Comment by chesskinx** [comment]
Hi @zerodytrash , having the problem too, need your help

**Comment by vivevainspira** [comment]
Same here, problemo with the server...please help @zerodytrash

**Comment by marioschwezenger** [comment]
me too, anybody can help me ?

**Comment by seahorse77** [comment]
Up, up, up, please help @zerodytrash

**Comment by blackbiron** [comment]
same issue here

**Comment by bradlynpeter** [comment]
thank you @zerodytrash...
