### ISSUE TITLE
Emit RoomInfo to the client

### ISSUE THREAD

**Issue by OlegShklyarov** [zerodytrash/TikTok-Live-Connector#24]
Hello, I am trying to show HLS link in client`s console after connect. 

I have added this to connectionWrapper:

```
	this.connection.getRoomInfo().then(roomInfo => {
		this.log(`HLS URL: ${roomInfo.stream_url.flv_pull_url.HD1}`);
		this.emit(`HLS URL: ${roomInfo.stream_url.flv_pull_url.HD1}`);
		})
```

But client does not receive it, it is visible only only in bash console.

**Comment by zerodytrash** [comment]
The client-side and server-side wrappers used for [TikTok-Chat-Reader](https://github.com/zerodytrash/TikTok-Chat-Reader) does not include the `getRoomInfo` function. But you could easily add them to the wrapper. However, it is currently possible to get the room info by taking it from the connect result. I think the video pull url doesn't change, so you don't need to retrieve the `roomInfo` again during the connection. Therefore this should be sufficient.

```javascript
connection.connect('@username').then(state => {

    console.log(state.roomInfo.stream_url.flv_pull_url.HD1);
    
}).catch(err => console.error(err))
```

![image](https://user-images.githubusercontent.com/59258980/163854330-b04ee78c-10ee-4515-8ae1-149b44a4ccd8.png)

**Comment by zerodytrash** [comment]
btw it may make more sense to use `state.roomInfo.stream_url.hls_pull_url` instead `flv_pull_url` because HLS playback is better supported in web browsers. You can play it with VideoJS or paste the URL here: https://videojs.github.io/videojs-contrib-hls/

**Comment by OlegShklyarov** [comment]
Thank you for your help, I will try.

**Comment by OlegShklyarov** [comment]
Should I just add it like that?

```
const { WebcastPushConnection } = require('tiktok-live-connector');
const { EventEmitter } = require('events');

let globalConnectionCount = 0;

/**
 * TikTok LIVE connection wrapper with advanced reconnect functionality and error handling
 */
 
 		connection.connect(uniqueId).then(state => {
        console.log(state.roomInfo.stream_url.flv_pull_url.HD1);
        }).catch(err => console.error(err))
```

**Comment by zerodytrash** [comment]
No, on client side, https://github.com/zerodytrash/TikTok-Chat-Reader/blob/d011ad941b85e27c59919dde3df0132dbcc07456/public/app.js#L25-L38

**Comment by OlegShklyarov** [comment]
We do not deserve people like you. Many thanks.
