### ISSUE TITLE
empty "roomInfo" and still connecting to offline user

### ISSUE THREAD

**Issue by rwmb** [zerodytrash/TikTok-Live-Connector#244]
Everytime I run `liveConnector.getRoomInfo()` it returns an empty object. This is happening for every user I try it with.
```javascript
roomInfo {
  "prompts": ""
}
```

Because of this I can't check if the user is online or not like I was doing before, and when I try to connect to an offline user, I get connected even though they are not streaming (not sure if it's related). Everything else is working fine; if the user is online, it connects and works normally; for some users I get the "UserOfflineError", but for other I can still connect even though they are offline.

For this reason I never know if it's connecting to the correct room or not and if it will get any events, which it doesn't if I start the service before the users starts their livestreams.

Any help or workaround?

**Comment by rwmb** [comment]
Testing a bit more (with the exact same code), I've noticed that it's not always that this happens and it's specific to a few users. Now it is returning the complete `roomInfo` again, but nothing has changed apart from the user making a livestream.

**Comment by zerodytrash** [comment]
fixed by @isaackogan, please update to the latest version (v1.2.1)
