### ISSUE TITLE
Cannot read properties of undefined (reading 'status')

### ISSUE THREAD

**Issue by qrq** [zerodytrash/TikTok-Live-Connector#245]
Error event triggered: Error while connecting, TypeError: Cannot read properties of undefined (reading 'status')
{
  info: 'Error while connecting',
  exception: TypeError: Cannot read properties of undefined (reading 'status')
      at WebcastPushConnection.connect (C:\Unity\Node\node_modules\tiktok-live-connector\dist\index.js:289:51)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
}

**Comment by kkpo4553** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the connect method to add error handling and checks for the response object to prevent 'Cannot read properties of undefined (reading 'status')' error.

You can review changes in this commit: https://github.com/kkpo4553/zerodytrash-TikTok-Live-Connector-245/commit/6b792efbe906a55e0c7f292a09b822c0782451dc.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by qrq** [comment]
i think isaackogan fix this error in :
Fix: [https://github.com/zerodytrash/TikTok-Live-Connector/pull/246](https://github.com/zerodytrash/TikTok-Live-Connector/pull/246)

**Comment by zerodytrash** [comment]
Merged! thanks @isaackogan
