### ISSUE TITLE
Failed to retrieve room_id from page source. Request failed with status code 403

### ISSUE THREAD

**Issue by ThanoFish** [zerodytrash/TikTok-Live-Connector#25]
I've been randomly getting this error for days now. It works for many hours, and then it just starts saying this and doesn't until the next day. Am I being rate limited or...?

**Comment by foxodever** [comment]
> I've been randomly getting this error for days now. It works for many hours, and then it just starts saying this and doesn't until the next day. Am I being rate limited or...?

Are u Russian? Because if yes, i have answer

**Comment by zerodytrash** [comment]
Sometimes IPs are blocked by TikTok. Do you use your own node server or do you use the server from https://tiktok-chat-reader.zerody.one/ ? 

If you run it locally, changing your IP may help.

**Comment by ThanoFish** [comment]
> > I've been randomly getting this error for days now. It works for many hours, and then it just starts saying this and doesn't until the next day. Am I being rate limited or...?
> 
> Are u Russian? Because if yes, i have answer

no



> Sometimes IPs are blocked by TikTok. Do you use your own node server or do you use the server from https://tiktok-chat-reader.zerody.one/ ?
> 
> If you run it locally, changing your IP may help.

i run it through repl.it

**Comment by zerodytrash** [comment]
> i run it through repl.it

I think with repl.it you share an IP address with many other users. If other people spam TikTok with requests over the same IP then the IP might be blocked. Maybe you can run it locally on your system or use the backend of [TikTok-Chat-Reader](https://github.com/zerodytrash/TikTok-Chat-Reader)

**Comment by foxodever** [comment]
> > > I've been randomly getting this error for days now. It works for many hours, and then it just starts saying this and doesn't until the next day. Am I being rate limited or...?
> > 
> > 
> > Are u Russian? Because if yes, i have answer
> 
> no
> 
> > Sometimes IPs are blocked by TikTok. Do you use your own node server or do you use the server from https://tiktok-chat-reader.zerody.one/ ?
> > If you run it locally, changing your IP may help.
> 
> i run it through repl.it

Well okay. Maybe repl.it ip is banned in tiktok
