### ISSUE TITLE
Strange issue with gift-repeat 

### ISSUE THREAD

**Issue by goontea** [zerodytrash/TikTok-Live-Connector#29]
Hello,

There seems to be a new strange issue with the data.gift.repeat_end = 1 not firing, but only for some gifters. I've made sure everything is up to date, and have even tried pointing the https://tiktok-chat-reader.zerody.one/ demo at a room.

From what I can tell, it seems to effect Australian gifters (not the host). I pointed the demo at an Australian live and these gifts of 1 roses show a red x1 that never turn black.
![image](https://user-images.githubusercontent.com/93460851/165897188-b43abebb-d50f-44a0-8517-d63de7da6b21.png)

Point it at an American live and they turn black (indicating the repeat_end gift event fired):
![image](https://user-images.githubusercontent.com/93460851/165897824-cbe84f4f-cd01-40bd-8b3d-6d4d5498e684.png)

Had the gifter try the same American room and only the initial gift (repeat_end = 0) fired in the same way as the Australian one.

**Comment by OlegShklyarov** [comment]
Same issue today.

**Comment by goontea** [comment]
Thanks! I think the problem has resolved itself now.

Tiktok glitch? Will update thread if it happens again.
