### ISSUE TITLE
Current viewers

### ISSUE THREAD

**Issue by wbillman** [zerodytrash/TikTok-Live-Connector#30]
Would it be possible to list the viewers that are watching the live under the number of viewers please

**Comment by zerodytrash** [comment]
At the moment this is not possible with this library. TikTok does not provide a viewer list. Only the number of viewers can be determined. If anyone knows a way to retrieve the current audience, let me know.

**Comment by kamilkmita** [comment]
But i dont know someone is leaving, can we handle this anyway ?

**Comment by zodcas** [comment]
Top Viewers list? I know it only shows top 99 via web but its a list that does update.

**Comment by introfaart** [comment]
> Top Viewers list? I know it only shows top 99 via web but its a list that does update.

i am looking for this setting too. any update ?

**Comment by zerodytrash** [comment]
> i am looking for this setting too. any update ?

Top viewers are available via `romUser` Event.
See https://github.com/zerodytrash/TikTok-Live-Connector#roomuser
