### ISSUE TITLE
 userBadges object is always empty, even when a sender is a Moderator

### ISSUE THREAD

**Issue by Sl4yZ** [zerodytrash/TikTok-Live-Connector#32]
Hello,

I found a bug in the data structure of userBadges object when receiving a chat, it's always empty, no matter if the sender is a Moderator or not.
Is it related to this library or the issue is from TikTok's API ?

**Comment by zerodytrash** [comment]
I will check. It is possible that the data structure has been changed by tiktok.

**Comment by zerodytrash** [comment]
Should be fixed in the latest version.
