### ISSUE TITLE
Can I join room with current info user ?

### ISSUE THREAD

**Issue by ToanNguyen97** [zerodytrash/TikTok-Live-Connector#36]
- It's seems join room as a guest user now, right ?
- The feature "Chat in live stream" use current sessionId to send message, it's awsome. So How I can join room with current info while I logged in ?.
- I try to push cookie to api /room/enter but it isn't working for me.

**Comment by zerodytrash** [comment]
> It's seems join room as a guest user now, right ?

Yes.

> The feature "Chat in live stream" use current sessionId to send message, it's awsome. So How I can join room with current info while I logged in ?.

You want to join the room with an account so that you are counted as a registered viewer? In this case, additional authentication steps are probably required for the websocket connection. Have never tried this.

Can you explain what you need this for?

**Comment by ToanNguyen97** [comment]
Thank for your answer, I just want to explore all api tiktok and I was just wondering if it's possible like a real user to interact with the live stream ?

**Comment by zerodytrash** [comment]
This would be possible with further reverse engineering measures. But I think this requirement is not so common. So I don't think I will work on it.

**Comment by ToanNguyen97** [comment]
Yup! Thank for your info !
