### ISSUE TITLE
403 profile picture error

### ISSUE THREAD

**Issue by Loathen** [zerodytrash/TikTok-Live-Connector#37]
Hello. A lot of profile pictures started to return a 403 error. Can you tell me what is the reason for this?

**Comment by zerodytrash** [comment]
hi, does this also happen on https://tiktok-chat-reader.zerody.one/ ?
Also check that you are using the latest version of the library.

**Comment by Loathen** [comment]
Yes, we use latest version of the library. On your site all ok, but on my server i have so many errors
<img width="553" alt="Снимок экрана 2022-06-17 в 20 30 05" src="https://user-images.githubusercontent.com/98689368/174349046-025ca103-bc53-42c3-8a4f-8afccd2fd53f.png">

**Comment by Loathen** [comment]
https://p58-sign-va.tiktokcdn.com/tos-maliva-avt-0068/f80fe9d7e6ece8c1b651ef526fe44dd0~c5_100x100.webp?x-expires=1655658000&x-signature=AfOKszWxrDWfAAhLSrnt8O+FdUM=
Example of url with error

**Comment by zerodytrash** [comment]
Have fixed the URL:
https://p58-sign-va.tiktokcdn.com/tos-maliva-avt-0068/f80fe9d7e6ece8c1b651ef526fe44dd0~c5_100x100.webp?x-expires=1655658000&x-signature=AfOKszWxrDWfAAhLSrnt8O%2BFdUM%3D

`+` => `%2B`
`=` => `%3D`

Special characters must be urlencoded. But this is the case by default. Do you use a decode function like `decodeURIComponent()`? If so, remove the decode function and use the original URL without any changes.

**Comment by Loathen** [comment]
Oy, really. Thank you so much
