### ISSUE TITLE
topGifterRank data always null

### ISSUE THREAD

**Issue by stephenmhudak** [zerodytrash/TikTok-Live-Connector#39]
Anytime a gift is sent, the topGifterRank data is null, even if the gifter is in top 3.

**Comment by stephenmhudak** [comment]
Apologies. Left out that this is when a gift event has been logged.

**Comment by zerodytrash** [comment]
I assume that TikTok does not transmit the topGifterRank for gift events because it is not relevant for the UI. As a workaround, you can cache the rank at chat, member and social events and use it at gift events.
