### ISSUE TITLE
All events stopped working

### ISSUE THREAD

**Issue by OlegShklyarov** [zerodytrash/TikTok-Live-Connector#42]
Could you please check from your side? We get no events.

**Comment by renelima** [comment]
Here it also stopped working

**Comment by adierebel** [comment]
maybe tiktok update their webcats, no event sent

**Comment by renelima** [comment]
Could it be that live-connector no longer works?

**Comment by asdfg314284230** [comment]
I have the same problem

**Comment by pbreit1988** [comment]
Can we use all the same source code? Copy Paste? Or must we generate something by our self?

**Comment by zerodytrash** [comment]
> Can we use all the same source code? Copy Paste? Or must we generate something by our self?

You need to extract the cookies (`sessionid` and `ttwid`) from your browser. The cookies mentioned in the example are invalid.

**Comment by zerodytrash** [comment]
> I think the problem is that when I'm live I can't watch my own stream at the same time. So it could be that my sessionid does not allow me to connect to the stream.

The session id is valid for all streams. You don't have to renew it every time.

**Comment by pbreit1988** [comment]
Okay i test it. Thank you for your Support.

**Comment by renelima** [comment]
> 

Here too! Did not work

**Comment by OlegShklyarov** [comment]
> It's been solved. thank you

How? Share you cure

**Comment by OlegShklyarov** [comment]
Should we change the connectionWrapper? 

`this.connection = new WebcastPushConnection(uniqueId, options);`

**Comment by guzinhoo** [comment]
```
this.connection = new WebcastPushConnection(uniqueId, {
	requestHeaders: {
		"Cookie": "sessionid=f6324878b8b34dbb8f86f1a2aafe5a0a;",
	},
});
```
Only this here solved my problem, I didn't put the ttwid and it worked normal

**Comment by OlegShklyarov** [comment]
> ```
> this.connection = new WebcastPushConnection(uniqueId, {
> 	requestHeaders: {
> 		"Cookie": "sessionid=f6324878b8b34dbb8f86f1a2aafe5a0a;",
> 	},
> });
> ```
> 
> Only this here solved my problem, I didn't put the ttwid and it worked normal

Thank you for the example. I wonder will it work for any user...

**Comment by OlegShklyarov** [comment]
I just use this on a client side:

```
socket.connect(uniqueId, {
    requestHeaders: {
"Cookie": "sessionid=7877777773c2fedf3923ce3c4;",
},
enableWebsocketUpgrade:false,
requestPollingIntervalMs: 500,
```

For how long is the session valid?

**Comment by adierebel** [comment]
> For how long is the session valid?

90 days

**Comment by OlegShklyarov** [comment]
And if I will relog on that browser, session will be terminated?

**Comment by zerodytrash** [comment]
> And if I will relog on that browser, session will be terminated?

Simply remove the cookie and you will be able to log in again without revoking the previous cookie.

**Comment by diazndc** [comment]
I've been trying to get it to work, but solution presented by zerody don't seem to work for me. Here's a [video](https://youtu.be/JvHyivp5VWs) a make of me retrieving the sessionid and ttwid and inserting it into socketHeaders and requestHeaders. 

It is also not upgrading to websocket.  Any ideas?

https://youtu.be/JvHyivp5VWs

**Comment by zerodytrash** [comment]
@diazndc try to delete all cookies from your browser. log in again. visit a livestream and then take the cookies.

**Comment by quang1412** [comment]
> Seems like TikTok no longer allows access to the webcast service without authentication. Adding a valid `sessionid` and the `ttwid` cookie seems to fix the problem.
> 
> ```js
> let tiktokChatConnection = new WebcastPushConnection('kingmohehe', {
>     requestHeaders: {
>         "Cookie": "sessionid=f6324878b8b34dbb8f86f1a2aafe5a0a; ttwid=1%7CLw5aVXrdJshrcdKNG2-zgC617ecDJ2WsxVHMymzZArQ%7C1658320010%7C03913e3ebc15cda442d9164e4f3f426544564573935abce01da09a557fa5130b;",
>     },
>     websocketHeaders: {
>         "Cookie": "sessionid=f6324878b8b34dbb8f86f1a2aafe5a0a; ttwid=1%7CLw5aVXrdJshrcdKNG2-zgC617ecDJ2WsxVHMymzZArQ%7C1658320010%7C03913e3ebc15cda442d9164e4f3f426544564573935abce01da09a557fa5130b;",
>     }
> });
> ```

It's been solved. thank you

**Comment by diazndc** [comment]
> @diazndc try to delete all cookies from your browser. log in again. visit a livestream and then take the cookies.

I've tried that. Tried also in a incognito window. Tried clearing not only cookies, but session storage and local storage aswell. I'll post another video soon trying your latest recomendation. Just to make sure.

**Comment by diazndc** [comment]
@zerodytrash here's a new attempt recorded https://youtu.be/aBmTo9--xx4

Could it be that webcast is being asked for an "if it's a robot" challenge?

**Comment by zerodytrash** [comment]
@diazndc it probably works because i have released a new version v0.9.22.
In this version, a sessionid may no longer be required.
maybe someone can test and confirm this.

update command: `npm i tiktok-live-connector`

**Comment by diazndc** [comment]
@zerodytrash  i still had 0.9.22 when it worked, now it stopped working again WebcastResponse.data.Buffer is always empty, again. I will update to the new version and see if it works

**Comment by diazndc** [comment]
@zerodytrash  yep the new version is working, thank you!

**Comment by linhnguyen9988** [comment]
@diazndc it still need sessionId but in 0.9.23 backend do it for you

**Comment by quang1412** [comment]
all events stopped working :(((
