### ISSUE TITLE
websocket: false

### ISSUE THREAD

**Issue by Daviko290** [zerodytrash/TikTok-Live-Connector#45]
when i try to start the server in visualstudio code i get this error websocket: false
has happened to someone else thanks

**Comment by zerodytrash** [comment]
have just released a new version. please update
`npm i tiktok-live-connector`
and check if the problem persists

**Comment by Daviko290** [comment]
If I already tried the last update:
├── dotenv@16.0.0
├──express@4.17.2
├── socket.io@4.4.1
└── tiktok-live-connector@0.9.22
and the result is the same although if I run it directly from index.html it works

**Comment by zerodytrash** [comment]
the newest version is tiktok-live-connector@0.9.23

**Comment by Daviko290** [comment]
I already updated everything I have the same error
├── dotenv@16.0.1
├──express@4.18.1
├── socket.io@4.5.1
└── tiktok-live-connector@0.9.23
I don't know what could be wrong until visualstudio restart it

**Comment by Daviko290** [comment]
I only have this error
WRAPPER @silekka: Connected to roomId 7122945039847820038, websocket: false

**Comment by zerodytrash** [comment]
please provide the code to establish the connection and the full console output.

**Comment by Daviko290** [comment]
I'm testing with the updated demo I downloaded it to see if the problem was in my code but the same thing happens with the demo I don't know if it will be some internet restriction until yesterday everything worked

**Comment by linhnguyen9988** [comment]
> have just released a new version. please update `npm i tiktok-live-connector` and check if the problem persists

new version 0.9.23 work perfectly without sessionid

**Comment by Daviko290** [comment]
It's already working from one moment to another and it says websocket: true Thanks for the help

**Comment by Daviko290** [comment]
Of course, update to the latest version 0.9.23
