### ISSUE TITLE
How to play sound when someone like, comment, follow?

### ISSUE THREAD

**Issue by yehesmurf** [zerodytrash/TikTok-Live-Connector#48]

**Comment by odhier** [comment]
use Websocket

**Comment by OlegShklyarov** [comment]
We use java script to run audio on events

**Comment by dev-kain** [comment]
You can use the node libraries related to text to speech conversion (also known as TTS) or simply play the audio files you have prepared. These node libraries only need to be executed after the event receives the data, which seems to meet your needs.

Just like this
```
tiktokChatConnection.on('chat', data => {
    console.log(`${data.uniqueId} (userId:${data.userId}) writes: ${data.comment}`);
    // code play audio ...
})
```

**Comment by yehesmurf** [comment]
> You can use the node libraries related to text to speech conversion (also known as TTS) or simply play the audio files you have prepared. These node libraries only need to be executed after the event receives the data, which seems to meet your needs.
> 
> Just like this
> 
> ```
> tiktokChatConnection.on('chat', data => {
>     console.log(`${data.uniqueId} (userId:${data.userId}) writes: ${data.comment}`);
>     // code play audio ...
> })
> ```

how to triggered follow events? when someone follow host?

**Comment by Kain-90** [comment]
You can try this.
```
tiktokChatConnection.on('social', data => {
    console.log('social event data:', data);
})
```
