### ISSUE TITLE
Events stopped after about 1-2 minutes

### ISSUE THREAD

**Issue by mostor-v** [zerodytrash/TikTok-Live-Connector#51]
Hi, 
I'm running demo code from readme ( connect and read some events)
But after of 1-2 minutes of running the script the events are stopped to be printing to console. After rerun script for a few times i have same problem. 1-3 minutes of events are printed and then stopped

Also I had error events that unable to upgrade to websockets. After i set ```enableWebsocketUpgrade: false``` error is not appears but events still not printed, and the same for raw data

**Comment by METAIRONY** [comment]
Hi, having the same issue

**Comment by zerodytrash** [comment]
is the disconnect event triggered?

**Comment by NWucha** [comment]
I dont recieve info from events

**Comment by zerodytrash** [comment]
I have tested it and the connection remains until the stream ends.

- Check if the library is up to date. Command: `npm update`
- Check if you are using a up to date NodeJS version.

**Comment by NWucha** [comment]
Checked but no results

**Comment by mostor-v** [comment]
Yeah, few last days works fine. Didn't change anything
