### ISSUE TITLE
Pls add ts or @types to npm, i can't work with ts

### ISSUE THREAD

**Issue by vsirenko** [zerodytrash/TikTok-Live-Connector#53]
![telegram-cloud-photo-size-2-5445288640746995361-y](https://user-images.githubusercontent.com/81309430/183456376-d44f17fa-2674-41bf-b5a5-799625f26155.jpg)

**Comment by zerodytrash** [comment]
will try

**Comment by zerodytrash** [comment]
can you check if this works?

**Comment by zerodytrash** [comment]
i believe it works.
