### ISSUE TITLE
I can't get isSubscriber or topGifterRank to get me any value other than false and null on user gifting

### ISSUE THREAD

**Issue by affluentmind** [zerodytrash/TikTok-Live-Connector#55]
As the title says, on gifting the 2 values always returns false or null and never anything else, am i not using it correctly? or is it not working I'm not sure

Also the subscribe event, does it capture the moment when someone subscribes? I wasn't successful of getting that to work either

**Comment by affluentmind** [comment]
Also the subscribe event, does it capture the moment when someone subscribes? I wasn't successful of getting that to work either

**Comment by zerodytrash** [comment]
> As the title says, on gifting the 2 values always returns false or null and never anything else, am i not using it correctly? or is it not working I'm not sure

TikTok does not transmit the info at Gift events because it is not relevant to the UI. You can try to cache the info from other events and then use it in Gift events.

> Also the subscribe event, does it capture the moment when someone subscribes? I wasn't successful of getting that to work either.

Yes, the subscribe event is still very buggy. TikTok does not have a dedicated subscribe event. This library uses some tricks to detect subscriptions. Unfortunately this does not work so well.

**Comment by zerodytrash** [comment]
I made changes to the subscribe event. Can you test it again with the current version (0.9.29)?

**Comment by affluentmind** [comment]
> I made changes to the subscribe event. Can you test it again with the current version (0.9.29)?

Sure thing, I will be sure to try it out and letting you know asap

**Comment by affluentmind** [comment]
Quick update I wasn't given the opportunity to try the subscribe event, but now the isSubscriber correctly shows values true or false based on subscription status, and I noticed that the subscribe event doesn't randomly fire as before so i will assume it works since everything works. I will be sure to post updates as further tests are being made.

thank you very much for the work done, much appreciated )

**Comment by zerodytrash** [comment]
I'll close this for now. Feel free to share the results of your tests.
