### ISSUE TITLE
Chat messages skipping

### ISSUE THREAD

**Issue by vladosnik** [zerodytrash/TikTok-Live-Connector#60]
Hello i am from Ukraine and my english is bad and i faced with problem, when your stream watching few people it's ok to use this library and i can get every message from chat, but if my stream watching from 300 to 1.5k people and every body writing messages to chat, this TikTol-Live-Connector lib starts skipping chat messages, when i compare it with tiktok chat on my device it looks like messages come in batches and this tiktok live connector library just showing the last message, you know tiktok server sending like 5-10 messages same time and library only shows last one, please test this on very active stream and see what i am trying to describe! if you understand me please tell me what to do to fix it somehow, maybe i can get messages in some kind of array?

**Comment by zerodytrash** [comment]
will check this.

**Comment by vladosnik** [comment]
thank you for fast reply, i love your live connector! it's the best! I was trying do do this kind of socket connection but i failed, when i saw this library it was like blessing to me

**Comment by vladosnik** [comment]
May be something wrong with my code i have frontend and backend app, my backend code looks like this

`
const {WebcastPushConnection} = require('tiktok-live-connector')
let tiktokUsername = 'nester4340'


let stream = new WebcastPushConnection(tiktokUsername)

stream.connect().then(state=>{
	console.info(`Подключено к комнате roomId ${state.roomId}`)
}).catch(e => {
	console.error('Ошибка подключения',e)
})


var WebSocketServer = require('websocket').server;
var http = require('http');

var server = http.createServer(function(request, response) {
    console.log((new Date()) + 'Received request for ' + request.url);
    response.writeHead(404);
    response.end();
});

server.listen(1234, function() {
    console.log(`Сервер запущен, порт 1234 ${Date.now()}`);
});

wsServer = new WebSocketServer({
    httpServer: server,
    autoAcceptConnections: false
});

function originIsAllowed(origin) {
  return true;
}

wsServer.on('request', function(request) {
    if (!originIsAllowed(request.origin)) {
      request.reject();
      console.log((new Date()) + ' Connection from origin ' + request.origin + ' rejected.');
      return;
    }
    
    var connection = request.accept('echo-protocol', request.origin);
    
    console.log(`Соединение принято ${connection.remoteAddress} ${Date.now()}`);
   


    stream.on('chat',data=>{
		console.log('chat',data.uniqueId,data.comment)
		connection.sendUTF(JSON.stringify({type:'chat',payload:data}));
	})


    stream.on('like', data => {
		connection.sendUTF(JSON.stringify({type:'like',payload:data}));

	})

    connection.on('close', function(reasonCode, description) {
        console.log(`Пир ${connection.remoteAddress} отключен!`);
    });



});

`

**Comment by vladosnik** [comment]
i am also sending tiktok messages from backend to frontend via websocket library maybe it has some delay or it's just skips messages? i can show you my code but it's very boilerplate i don't think that problem in my code

backend: `
const {WebcastPushConnection} = require('tiktok-live-connector')
let tiktokUsername = 'nester4340'


let stream = new WebcastPushConnection(tiktokUsername)

stream.connect().then(state=>{
}).catch(e => {
	console.log(e)
})


var WebSocketServer = require('websocket').server;
var http = require('http');

var server = http.createServer(function(request, response) {
    response.writeHead(404);
    response.end();
});

server.listen(1234, function() {});

wsServer = new WebSocketServer({
    httpServer: server,
    autoAcceptConnections: false
});

function originIsAllowed(origin) {
  return true;
}

wsServer.on('request', function(request) {
    if (!originIsAllowed(request.origin)) {
      request.reject();
      return;
    }
    
    var connection = request.accept('echo-protocol', request.origin);
    
    stream.on('chat',data=>{
		connection.sendUTF(JSON.stringify({type:'chat',payload:data}));
	})


    stream.on('like', data => {
		connection.sendUTF(JSON.stringify({type:'like',payload:data}));
	})

    connection.on('close', function(reasonCode, description) {
        console.log('disconnect');
    })

})

`

**Comment by zerodytrash** [comment]
Please use this code for testing:

```javascript
const { WebcastPushConnection } = require('tiktok-live-connector');

let connection = new WebcastPushConnection('@user');

connection.on('chat', data => console.log(data.uniqueId, data.comment));

connection.connect().catch(err => console.error(err));
```

...And see if the problem also occurs with that code.

**Comment by vladosnik** [comment]
Ok i will try it

**Comment by vladosnik** [comment]
OK i just tested, looks like it's working fine. I am sorry about that

**Comment by vladosnik** [comment]
I fixed my code, it works nice, solution was too simple, i created array of messages and each time message come i just write it to array, and then i use setInterval(render, 100) and each 100 ms the first message of array showing up and removing from array so if somebody needs this kind of functionality this is how i made it

**Comment by vladosnik** [comment]
Thank you author for such amazing library, 9999 likes to you

**Comment by zerodytrash** [comment]
Thanks! Good to hear that everything is working now :)

**Comment by vladosnik** [comment]
> Thanks! Good to hear that everything is working now :)

i wanted to donate you but i have problem with my bank, the reason is war in my country i can't send money out of country
