### ISSUE TITLE
"subscribe" event don't work

### ISSUE THREAD

**Issue by HelloWorld537** [zerodytrash/TikTok-Live-Connector#64]
hello. thank you for the nice Library.
But tiktokLiveConnection.on('subscribe', (data) => {
    console.log(data.uniqueId, "subscribed!");
}) don't work. how i can fix it?

**Comment by HelloWorld537** [comment]
other events working nice, only this event just have no reactions

**Comment by zerodytrash** [comment]
hi, are you using the latest version v1.0.0?

**Comment by HelloWorld537** [comment]
> hi, are you using the latest version v1.0.0?

yes, i think.... this is my package.json  
{
  "dependencies": {
    "tiktok-live-connector": "^1.0.0"
  }
}
and after i make      npm update  and check it again, still don't working =(

**Comment by zerodytrash** [comment]
where are you testing this? subscriptions are very rare on tiktok and only some streamers have this feature.
are you confusing this with the "follow" event? see https://github.com/zerodytrash/TikTok-Live-Connector#follow

**Comment by HelloWorld537** [comment]
> where are you testing this? subscriptions are very rare on tiktok and only some streamers have this feature. are you confusing this with the "follow" event? see https://github.com/zerodytrash/TikTok-Live-Connector#follow

oh sorry, hahha. i needed follow event :D 
now everything works great. sorry for taking up your time. wish you success in your business!!!!
