### ISSUE TITLE
Connection failed, Error: Failed to sign request: Request failed with status code 429;

### ISSUE THREAD

**Issue by artwl** [zerodytrash/TikTok-Live-Connector#65]
This is a very interesting project that can be used to do a lot of interesting things, thanks a lot to the author!

I frequently encountered "Connection failed, Error: Failed to sign request: Request failed with status code 429" errors today

Want to know the following questions:

1. The 429 status code is generally an error because the request frequency is too frequent. I want to know whether this error is given by the official tiktok or the author's signature server.

2. I would like to know what the frequency limit is, whether it is calculated by the number of connections in the live broadcast room or by the frequency of message acceptance.

3. Can this signature server be deployed by itself? If so, is there a description of the deployment steps? If not, is there a paid solution to solve the 429 problem?

Thanks again for the author's efforts!

**Comment by zerodytrash** [comment]
> The 429 status code is generally an error because the request frequency is too frequent. I want to know whether this error is given by the official tiktok or the author's signature server.

The 429 error is raised by the signature service. It prevents people from mass connecting, data scraping, view botting and TikTok from blocking our signatures.

> I would like to know what the frequency limit is, whether it is calculated by the number of connections in the live broadcast room or by the frequency of message acceptance.

The current limit is 5 connection requests per minute and 30 per hour (IP-based). Furthermore, there is a node process based limit which restricts the connection to a maximum of 4 different broadcasters per 30 minutes.

> Can this signature server be deployed by itself? If so, is there a description of the deployment steps? If not, is there a paid solution to solve the 429 problem?

The setup for generating the signatures is very complex. Unfortunately we do not offer a self-hosted variant at the moment. The general problem with the publication of such software is that it would then be used on a massive scale and TikTok would improve their signature algorithm very quickly.

If you don't want to use the library for data scraping and spamming I can offer you an API key to make more connections :)

**Comment by artwl** [comment]
> > The 429 status code is generally an error because the request frequency is too frequent. I want to know whether this error is given by the official tiktok or the author's signature server.
> 
> The 429 error is raised by the signature service. It prevents people from mass connecting, data scraping, view botting and TikTok from blocking our signatures.
> 
> > I would like to know what the frequency limit is, whether it is calculated by the number of connections in the live broadcast room or by the frequency of message acceptance.
> 
> The current limit is 5 connection requests per minute and 30 per hour (IP-based). Furthermore, there is a node process based limit which restricts the connection to a maximum of 4 different broadcasters per 30 minutes.
> 
> > Can this signature server be deployed by itself? If so, is there a description of the deployment steps? If not, is there a paid solution to solve the 429 problem?
> 
> The setup for generating the signatures is very complex. Unfortunately we do not offer a self-hosted variant at the moment. The general problem with the publication of such software is that it would then be used on a massive scale and TikTok would improve their signature algorithm very quickly.
> 
> If you don't want to use the library for data scraping and spamming I can offer you an API key to make more connections :)

Thank you very much, our project is currently in testing, and we will contact you if we need it in the future, and are willing to pay for it!

**Comment by tranvanduong2483** [comment]
@zerodytrash Hi bro, I want a key with more connections, how can I contact you (my telegram id: @tranvanduong2483)

**Comment by Ravenglass** [comment]
> don't want to use the library for data scraping and spamming I can offer you an API key to make more connection

Hi... Does this offer still stand?

**Comment by zerodytrash** [comment]
> > don't want to use the library for data scraping and spamming I can offer you an API key to make more connection
> 
> Hi... @zerodytrash Does this offer still stand?

Yes.

**Comment by Ravenglass** [comment]
@zerodytrash thanx, just dropped you an email...
