### ISSUE TITLE
Error: Request failed with status code 403

### ISSUE THREAD

**Issue by crypxeo** [zerodytrash/TikTok-Live-Connector#72]
Error: Request failed with status code 403
How to solve it? A few hours ago everything was working fine.

**Comment by brogrammer1337** [comment]
Same problem

**Comment by zerodytrash** [comment]
Proxy IPs with recurring requests are currently blocked.

**Comment by crypxeo** [comment]
How to solve it? Or just wait a few hours and it will be automatically unblocked?

**Comment by f2face** [comment]
Same problem, but this doesn't happen to all @username, some other are just working fine.

**Comment by msTokens** [comment]
i was connected for hours normally now it cannot connect how to work like this who decides whats a proxy or not i am as sample using everything to normal just 1 connection and it not works currently it does not connect to my room.

**Comment by zerodytrash** [comment]
Is it fixed now? If not, what error code are you getting now?

**Comment by msTokens** [comment]
> Is it fixed now? If not, what error code are you getting now?

it works now. <3
