### ISSUE TITLE
Double gift event issue

### ISSUE THREAD

**Issue by plytki** [zerodytrash/TikTok-Live-Connector#73]
TikTok gifts are handled twice.
![image](https://user-images.githubusercontent.com/53957038/195920572-37dba3ae-245c-465f-8df2-6bf0eb27c2e5.png)
![image](https://user-images.githubusercontent.com/53957038/195920601-5f09bdfd-5ee0-4df0-a382-2000e72a5a7b.png)

**Comment by zerodytrash** [comment]
hi, please take a look at the documentation: https://github.com/zerodytrash/TikTok-Live-Connector#gift
You need to check `giftType` and `repeatEnd` and etc. Let me know if this fixes your issue.

**Comment by plytki** [comment]
Thanks! Solved!
