### ISSUE TITLE
The likeCount limited to 15 likes.

### ISSUE THREAD

**Issue by richjr93** [zerodytrash/TikTok-Live-Connector#76]
Hi, I have an issue with the like likeCount. it only logs up to 15 likes. How can I make it so that it doesn't stop at 15? It shouldn't be displaying the likeCount before the user stops tapping the screen. It should only show the final likeCount amount after the user stops tapping. Hope you can help me out with this. Thank you in advance!

**Comment by bslkh** [comment]
TikTok sends maximum 15 likes to the pool

You can store each pool per user and calculate the total when you need it.

**Comment by richjr93** [comment]
Hi, thanks for the reply. Would you mind to show me the exact way to do that? I'm afraid I have not much knowledge on coding😅

**Comment by bslkh** [comment]
Do you always need to show likes right after the user finishes their streak, or do you have an event after which you need to show the number of likes?

**Comment by richjr93** [comment]
Yes, I do want it to show the total likes from each respective user right after they finish their streak/screen tapping. Just to be clear, let's say they tapped 100 times non-stop and then they end their streak, it will show that they've sent 100 likes. If they tapped for 5000 times non-stop and then stopped, it will show that they've sent 5000 likes.

**Comment by bslkh** [comment]
I think until TikTok adds marks the start and end of the streak, it is difficult to determine with high accuracy, but you can choose your interval

I'm afraid I don't have much knowledge about coding either

example piece of code for server
`var list_users_likes = new Object();
tiktokLiveConnection.on('like', data => {
			if (list_users_likes.hasOwnProperty(data.uniqueId)) {
				list_users_likes[data.uniqueId].addTime();
				list_users_likes[data.uniqueId].up(data.likeCount);
			} else {
				list_users_likes[data.uniqueId] = {
					total: 0,
					uniqueId: data.uniqueId,
					dropLikes(total) {
						console.log(this.uniqueId, total); //do something you need
						this.timeoutID = undefined;
						delete list_users_likes[this.uniqueId];
					},
					addTime() {
						clearTimeout(this.timeoutID);
					},
					up(like) {
						this.total += like;
						this.timeoutID = setTimeout((total) => {
							this.dropLikes(total);
						}, 4000, this.total) //4 seconds interval
					}
				};
				list_users_likes[data.uniqueId].up(data.likeCount);
			}
})`

**Comment by richjr93** [comment]
Thanks for the code example. Do I just copy and paste or I still have to modify anything? If I were to replace a code from my file, do I replace the follow code?:
```
tiktokLiveConnection.on('like', data => {
    console.log(`${data.uniqueId} sent ${data.likeCount} likes, total likes: ${data.totalLikeCount}`);
})
```

**Comment by bslkh** [comment]
Other than the lines where there is a comment (11, 22), it is better not to change anything

Yes, this part of your code should be replaced to avoid duplicate

**Comment by richjr93** [comment]
Okay, I actually have a few differences in my code which make me kind of confused about what exactly my code should look like, I thought I could add your code just like that with a little bit of modification, but it didn't work out. Maybe you could modify the code based on what I currently have if you don't mind 😅.

Alright so I have a function **addMessageLike**, created to display the output:
```
function addMessageLike(data) {
        // Check setting
        if (confLike) {
            // Add
            addContent(`${data.uniqueId} sent ${data.likeCount} likes, total likes: ${data.totalLikeCount}`);

            // Sound
            playSound(1);
        }
        
    }
```
In the above function, I have a condition called **confLike** to proceed if only it's true.
I also have the **addContent**, which is just another function for where and how to display the content and the content is inside the bracket.
The following image is the current result(which is the issue I currently have where it only records up to 15 likes at a time, and then displays another 15, and so on.):
![image](https://user-images.githubusercontent.com/68835183/197158412-33cd4e2b-2823-4273-bdde-179a976f6ff6.png)

Here is my actual code for the connection:
```
connection.on('like', (data) => {
    if (typeof data.likeCount === 'number') {
            // Check setting
        if (confLike) {
        addMessageLike(data);
        }
    }
})
```
I also put the whole code [here](https://jsfiddle.net/richjr93/k218nLmu/) in case you want to have a look.
Hope those could help you more. Thanks!

**Comment by richjr93** [comment]
I'm not sure which file do I show for the data transfer set up 😅.
I actually downloaded the project from [here](https://github.com/alexdhg/tiktok-printer-live). I think it will be easier for you to understand the code if you can see it all. The code I've shown in my previous reply is from the **app.js** file that you can find inside **/public/assets/js**. But of course, I modified the **app.js** just a little bit. Originally it doesn't display the number of likes at all.

**Comment by bslkh** [comment]
Yes, I need to see how you change server.js and implemented the code I wrote earlier

**Comment by richjr93** [comment]
Oh. I didn't change anything in the **server.js** but what I did in **app.js** from the code you suggested earlier is:
1. From this code:
```
connection.on('like', (data) => {
    if (typeof data.likeCount === 'number') {
            // Check setting
        if (confLike) {
        addMessageLike(data);
        }
    }
})
```
I changed to this:
```
var list_users_likes = new Object();
connection.on('like', data => {
if (confLike) {
	if (list_users_likes.hasOwnProperty(data.uniqueId)) {
		list_users_likes[data.uniqueId].addTime();
		list_users_likes[data.uniqueId].up(data.likeCount);
	} else {
		list_users_likes[data.uniqueId] = {
			total: 0,
			uniqueId: data.uniqueId,
			dropLikes(total) {
				addMessage(this.uniqueId, total); //do something you need
				this.timeoutID = undefined;
				delete list_users_likes[this.uniqueId];
			},
			addTime() {
				clearTimeout(this.timeoutID);
			},
			up(like) {
				this.total += like;
				this.timeoutID = setTimeout((total) => {
					this.dropLikes(total);
				}, 4000, this.total) //4 seconds interval
			}
		};
		list_users_likes[data.uniqueId].up(data.likeCount);
	}
}})
```

Honestly, I don't even have any idea of what I modified, that's why I was confused 😅.

**Comment by bslkh** [comment]
😅

As far as I understand, that library has not been updated for a long time and does not work

In the case of likes, you just need to make sure that:
1. 'data' comes in the right format
2. slightly change code
(for example)
```
var list_users_likes = new Object();
connection.on('like', data => {
if (confLike) {
	if (list_users_likes.hasOwnProperty(data.uniqueId)) {
		list_users_likes[data.uniqueId].addTime();
		list_users_likes[data.uniqueId].up(data);
	} else {
		list_users_likes[data.uniqueId] = {
			total: 0,
			uniqueId: data.uniqueId,
			dropLikes(data) {
				addMessage(data); //do something you need
				this.timeoutID = undefined;
				delete list_users_likes[this.uniqueId];
			},
			addTime() {
				clearTimeout(this.timeoutID);
			},
			up(data) {
				this.total += data.likeCount;
				data.likeCount = this.total;
				this.timeoutID = setTimeout((data) => {
					this.dropLikes(data);
				}, 4000, data) //4 seconds interval
			}
		};
		list_users_likes[data.uniqueId].up(data);
	}
}})
```
3. addMessage or addMessageLike?

**Comment by richjr93** [comment]
OMG it worked! Thank you very much!!! the **addMessageLike** is actually a custom function I made to display the data for likes when only the **confLike** is true. Otherwise, it needs both **confLike** and **confComment** to work which I don't want because that way it will show the comments as well when I only want to see the likes. 😁

**Comment by bslkh** [comment]
I'm glad that I can some help you
