### ISSUE TITLE
Member leaves the stream event missing

### ISSUE THREAD

**Issue by LearningNewPlatforms** [zerodytrash/TikTok-Live-Connector#78]
https://github.com/zerodytrash/TikTok-Live-Connector#member
This event notifies when member joins the stream but there is no way to notify when member leaves

Can you please fix it?

**Comment by zerodytrash** [comment]
> > https://github.com/zerodytrash/TikTok-Live-Connector#member
> > This event notifies when member joins the stream but there is no way to notify when member leaves
> > Can you please fix it?
> 
> This is a TikTok problem. There is no leave stream event coming from TikTok.

correct.
