### ISSUE TITLE
error 403

### ISSUE THREAD

**Issue by spoofy9** [zerodytrash/TikTok-Live-Connector#82]
I get a 403 error on every stream.
I'm using a basic example.

**Comment by constSilent** [comment]
same problem

**Comment by crypxeo** [comment]
Today I get 403 error
Error: Request failed with status code 403

**Comment by thovan-bayard** [comment]
I got axios error with url
https://tiktok.isaackogan.com/webcast/fetch/?room_id=...
But it works fine at local. May be this website received too many requests from my server and block it for security reason...

**Comment by coladeu** [comment]
same :|

**Comment by adiantek** [comment]
any solution?
