### ISSUE TITLE
open Can not @client.on("error")

### ISSUE THREAD

**Issue by BILINGBALL** [zerodytrash/TikTok-Live-Connector#88]
@client.on("error")
async def on_error(error: Exception):
    print(error)
    # Handle the error
    if isinstance(error,(WebsocketConnectionFailed,FailedFetchRoomInfo,FailedHTTPRequest,FailedConnection,LiveNotFound,FailedParseUserHTML,FailedConnection,)):
        print("Handle Some Error")
        return

Is there anything wrong with such usement? It can't handle the error, even trigger the handler

**Comment by BILINGBALL** [comment]
I just donated $5 dollars on paypal but how do you know that was me ahh

**Comment by zerodytrash** [comment]
Hi, thanks for the donation but you are wrong here. According to your code you are using the python version: https://github.com/isaackogan/TikTokLive

**Comment by BILINGBALL** [comment]
thank you and I will delete it later.And go to python area
