### ISSUE TITLE
ERROR:root:Connection was lost to the Webcast Websocket Server. Restart the client connection to continue

### ISSUE THREAD

**Issue by LiamKrenn** [zerodytrash/TikTok-Live-Connector#95]
After running my program for a while I get this error:
`ERROR:root:Connection was lost to the Webcast Websocket Server. Restart the client connection to continue`
Then the program stops. How can I handle this / restart automatically?

**Comment by zerodytrash** [comment]
Wrong repo. Please create your issue here: https://github.com/isaackogan/TikTokLive
